version: '3.8'
services:
  backend:
    image: ghcr.io/OWNER/manga-reader-backend:master
    environment:
      - PORT=8000
    ports:
      - "8000:8000"

  frontend:
    image: ghcr.io/Apex-94/manga-reader-frontend:master
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
